### ISSUE TITLE
3days ago stop show entities

### ISSUE THREAD

**Issue by Jirik6** [EvanSchalton/tuya-homeassistant-openapi#3]
3days ago stop show entities.
sorry expired platform...

**Comment by EvanSchalton** [comment]
@Jirik6 mine is still working, did you change something in Tuya?

**Comment by Jirik6** [comment]
Ending 30days subscription on Tuya iot plarform. Now i have next 6month, but best way to future is integrate over local tuya. Txh JiriOdesláno z iPhonu18. 5. 2024 v 19:37, Evan Schalton ***@***.***>:﻿
@Jirik6 mine is still working, did you change something in Tuya?

**Comment by Jirik6** [comment]
But i dont have exprience with “add my unsupported device” here:tuya-local/custom_components/tuya_local/devices/README.md at main · make-all/tuya-localgithub.comThx JiriOdesláno z iPhonu18. 5. 2024 v 19:37, Evan Schalton ***@***.***>:﻿
@Jirik6 mine is still working, did you change something in Tuya?
