### ISSUE TITLE
adding integration / no text

### ISSUE THREAD

**Issue by peters59** [EvanSchalton/tuya-homeassistant-openapi#4]
I get only this view when adding the integration
![image](https://github.com/user-attachments/assets/a416c1d1-2ee1-4193-9d45-31f0f913e45c)

**Comment by EvanSchalton** [comment]
Hey, this is a duplicate of #2 https://github.com/EvanSchalton/tuya-homeassistant-openapi/issues/2#issuecomment-2062140315
